Importing libraries

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re
import os
import collections
import seaborn as sns
import plotly.express as px
import warnings
warnings.filterwarnings('ignore')
!pip3 install openpyxl

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: openpyxl in /usr/local/lib/python3.7/dist-packages (3.0.10)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.7/dist-packages (from openpyxl) (1.1.0)

Importing Dataset

In [ ]:
from google.colab import files
uploaded=files.upload()

Saving indian_rainfall 1901-2015.csv to indian_rainfall 1901-2015.csv

In [ ]:
import pandas as pd
import io
df = pd.read_csv(io.BytesIO(uploaded['indian_rainfall 1901-2015.csv']))
print(df)

                    SUBDIVISION  YEAR   JAN    FEB   MAR    APR    MAY    JUN  \
0     ANDAMAN & NICOBAR ISLANDS  1901  49.2   87.1  29.2    2.3  528.8  517.5
1     ANDAMAN & NICOBAR ISLANDS  1902   0.0  159.8  12.2    0.0  446.1  537.1
2     ANDAMAN & NICOBAR ISLANDS  1903  12.7  144.0   0.0    1.0  235.1  479.9
3     ANDAMAN & NICOBAR ISLANDS  1904   9.4   14.7   0.0  202.4  304.5  495.1
4     ANDAMAN & NICOBAR ISLANDS  1905   1.3    0.0   3.3   26.9  279.5  628.7
...                         ...   ...   ...    ...   ...    ...    ...    ...
4111                LAKSHADWEEP  2011   5.1    2.8   3.1   85.9  107.2  153.6
4112                LAKSHADWEEP  2012  19.2    0.1   1.6   76.8   21.2  327.0
4113                LAKSHADWEEP  2013  26.2   34.4  37.5    5.3   88.3  426.2
4114                LAKSHADWEEP  2014  53.2   16.1   4.4   14.9   57.4  244.1
4115                LAKSHADWEEP  2015   2.2    0.5   3.7   87.1  133.1  296.6

        JUL    AUG    SEP    OCT    NOV    DEC  ANNUAL  Jan-Feb  Mar-May  \
0     365.1  481.1  332.6  388.5  558.2   33.6  3373.2    136.3    560.3
1     228.9  753.7  666.2  197.2  359.0  160.5  3520.7    159.8    458.3
2     728.4  326.7  339.0  181.2  284.4  225.0  2957.4    156.7    236.1
3     502.0  160.1  820.4  222.2  308.7   40.1  3079.6     24.1    506.9
4     368.7  330.5  297.0  260.7   25.4  344.7  2566.7      1.3    309.7
...     ...    ...    ...    ...    ...    ...     ...      ...      ...
4111  350.2  254.0  255.2  117.4  184.3   14.9  1533.7      7.9    196.2
4112  231.5  381.2  179.8  145.9   12.4    8.8  1405.5     19.3     99.6
4113  296.4  154.4  180.0   72.8   78.1   26.7  1426.3     60.6    131.1
4114  116.1  466.1  132.2  169.2   59.0   62.3  1395.0     69.3     76.7
4115  257.5  146.4  160.4  165.4  231.0  159.0  1642.9      2.7    223.9

      Jun-Sep  Oct-Dec
0      1696.3    980.3
1      2185.9    716.7
2      1874.0    690.6
3      1977.6    571.0
4      1624.9    630.8
...       ...      ...
4111   1013.0    316.6
4112   1119.5    167.1
4113   1057.0    177.6
4114    958.5    290.5
4115    860.9    555.4

[4116 rows x 19 columns]

In [ ]:
from google.colab import files
uploaded=files.upload()

Saving district wise rainfall normal.csv to district wise rainfall normal.csv

In [23]:
import pandas as pd
import io
df1 = pd.read_csv(io.BytesIO(uploaded['district wise rainfall normal.csv']))
print(df1)

                   STATE_UT_NAME        DISTRICT    JAN   FEB    MAR    APR  \
0    ANDAMAN And NICOBAR ISLANDS         NICOBAR  107.3  57.9   65.2  117.0
1    ANDAMAN And NICOBAR ISLANDS   SOUTH ANDAMAN   43.7  26.0   18.6   90.5
2    ANDAMAN And NICOBAR ISLANDS   N & M ANDAMAN   32.7  15.9    8.6   53.4
3              ARUNACHAL PRADESH           LOHIT   42.2  80.8  176.4  358.5
4              ARUNACHAL PRADESH      EAST SIANG   33.3  79.5  105.9  216.5
..                           ...             ...    ...   ...    ...    ...
636                       KERALA          IDUKKI   13.4  22.1   43.6  150.4
637                       KERALA        KASARGOD    2.3   1.0    8.4   46.9
638                       KERALA  PATHANAMTHITTA   19.8  45.2   73.9  184.9
639                       KERALA         WAYANAD    4.8   8.3   17.5   83.3
640                  LAKSHADWEEP     LAKSHADWEEP   20.8  14.7   11.8   48.9

       MAY    JUN     JUL    AUG    SEP    OCT    NOV    DEC  ANNUAL  Jan-Feb  \
0    358.5  295.5   285.0  271.9  354.8  326.0  315.2  250.9  2805.2    165.2
1    374.4  457.2   421.3  423.1  455.6  301.2  275.8  128.3  3015.7     69.7
2    343.6  503.3   465.4  460.9  454.8  276.1  198.6  100.0  2913.3     48.6
3    306.4  447.0   660.1  427.8  313.6  167.1   34.1   29.8  3043.8    123.0
4    323.0  738.3   990.9  711.2  568.0  206.9   29.5   31.7  4034.7    112.8
..     ...    ...     ...    ...    ...    ...    ...    ...     ...      ...
636  232.6  651.6   788.9  527.3  308.4  343.2  172.9   48.1  3302.5     35.5
637  217.6  999.6  1108.5  636.3  263.1  234.9   84.6   18.4  3621.6      3.3
638  294.7  556.9   539.9  352.7  266.2  359.4  213.5   51.3  2958.4     65.0
639  174.6  698.1  1110.4  592.9  230.7  213.1   93.6   25.8  3253.1     13.1
640  171.7  330.2   287.7  217.5  163.1  157.1  117.7   58.8  1600.0     35.5

     Mar-May  Jun-Sep  Oct-Dec
0      540.7   1207.2    892.1
1      483.5   1757.2    705.3
2      405.6   1884.4    574.7
3      841.3   1848.5    231.0
4      645.4   3008.4    268.1
..       ...      ...      ...
636    426.6   2276.2    564.2
637    272.9   3007.5    337.9
638    553.5   1715.7    624.2
639    275.4   2632.1    332.5
640    232.4    998.5    333.6

[641 rows x 19 columns]

Handling Missing Values

In [24]:
df.isnull().any()

SUBDIVISION    False
YEAR           False
JAN             True
FEB             True
MAR             True
APR             True
MAY             True
JUN             True
JUL             True
AUG             True
SEP             True
OCT             True
NOV             True
DEC             True
ANNUAL          True
Jan-Feb         True
Mar-May         True
Jun-Sep         True
Oct-Dec         True
dtype: bool

In [25]:
df1.isnull().any()

STATE_UT_NAME    False
DISTRICT         False
JAN              False
FEB              False
MAR              False
APR              False
MAY              False
JUN              False
JUL              False
AUG              False
SEP              False
OCT              False
NOV              False
DEC              False
ANNUAL           False
Jan-Feb          False
Mar-May          False
Jun-Sep          False
Oct-Dec          False
dtype: bool

There is a missing values in dataset of "rainfall in india 1901=2015.csv"

In [26]:
df.isnull().sum()

SUBDIVISION     0
YEAR            0
JAN             4
FEB             3
MAR             6
APR             4
MAY             3
JUN             5
JUL             7
AUG             4
SEP             6
OCT             7
NOV            11
DEC            10
ANNUAL         26
Jan-Feb         6
Mar-May         9
Jun-Sep        10
Oct-Dec        13
dtype: int64

In [27]:
df1.isnull().sum

<bound method NDFrame._add_numeric_operations.<locals>.sum of      STATE_UT_NAME  DISTRICT    JAN    FEB    MAR    APR    MAY    JUN    JUL  \
0            False     False  False  False  False  False  False  False  False
1            False     False  False  False  False  False  False  False  False
2            False     False  False  False  False  False  False  False  False
3            False     False  False  False  False  False  False  False  False
4            False     False  False  False  False  False  False  False  False
..             ...       ...    ...    ...    ...    ...    ...    ...    ...
636          False     False  False  False  False  False  False  False  False
637          False     False  False  False  False  False  False  False  False
638          False     False  False  False  False  False  False  False  False
639          False     False  False  False  False  False  False  False  False
640          False     False  False  False  False  False  False  False  False

       AUG    SEP    OCT    NOV    DEC  ANNUAL  Jan-Feb  Mar-May  Jun-Sep  \
0    False  False  False  False  False   False    False    False    False
1    False  False  False  False  False   False    False    False    False
2    False  False  False  False  False   False    False    False    False
3    False  False  False  False  False   False    False    False    False
4    False  False  False  False  False   False    False    False    False
..     ...    ...    ...    ...    ...     ...      ...      ...      ...
636  False  False  False  False  False   False    False    False    False
637  False  False  False  False  False   False    False    False    False
638  False  False  False  False  False   False    False    False    False
639  False  False  False  False  False   False    False    False    False
640  False  False  False  False  False   False    False    False    False

     Oct-Dec
0      False
1      False
2      False
3      False
4      False
..       ...
636    False
637    False
638    False
639    False
640    False

[641 rows x 19 columns]>

In [28]:
df.shape

(4116, 19)

In [29]:
df = df.dropna(axis = 0, how ='any')
df.shape

(4090, 19)

In [30]:
df.isnull().any()

SUBDIVISION    False
YEAR           False
JAN            False
FEB            False
MAR            False
APR            False
MAY            False
JUN            False
JUL            False
AUG            False
SEP            False
OCT            False
NOV            False
DEC            False
ANNUAL         False
Jan-Feb        False
Mar-May        False
Jun-Sep        False
Oct-Dec        False
dtype: bool

In [31]:
df.describe()

,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL,Jan-Feb,Mar-May,Jun-Sep,Oct-Dec
count,4090.000000,4090.000000,4090.000000,4090.000000,4090.000000,4090.000000,4090.000000,4090.000000,4090.000000,4090.000000,4090.000000,4090.000000,4090.000000,4090.000000,4090.000000,4090.000000,4090.000000,4090.000000
mean,1958.321271,18.818484,21.644792,27.252494,42.714548,84.868044,228.928020,346.496968,289.897506,197.003056,95.139022,39.548191,18.695575,1411.008900,40.462861,154.835452,1062.325575,153.384499
std,33.148944,33.521719,35.762010,46.829179,67.264863,122.556801,233.535693,269.352685,187.702293,135.266708,99.325638,68.275513,42.185553,903.846565,59.136229,200.315769,705.970202,166.414108
min,1901.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.400000,0.000000,0.000000,0.100000,0.000000,0.000000,0.000000,62.300000,0.000000,0.000000,57.400000,0.000000
25%,1930.000000,0.600000,0.600000,1.000000,3.000000,8.500000,70.000000,175.225000,155.925000,100.400000,14.600000,0.700000,0.100000,804.500000,4.100000,23.800000,573.275000,34.025000
50%,1959.000000,5.900000,6.600000,7.800000,15.500000,36.050000,138.450000,284.300000,259.500000,173.600000,64.650000,9.500000,3.000000,1121.300000,19.000000,74.250000,880.200000,97.550000
75%,1987.000000,21.950000,26.600000,31.100000,49.375000,94.975000,302.250000,416.700000,377.775000,265.600000,148.100000,45.475000,17.300000,1644.775000,50.200000,195.300000,1286.175000,211.800000
max,2015.000000,583.700000,403.500000,605.600000,595.100000,1168.600000,1609.900000,2362.800000,1664.600000,1222.000000,948.300000,648.900000,617.500000,6331.100000,699.500000,1745.800000,4536.900000,1252.500000

In [32]:
df1.describe()

,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL,Jan-Feb,Mar-May,Jun-Sep,Oct-Dec
count,641.000000,641.000000,641.000000,641.000000,641.000000,641.000000,641.000000,641.000000,641.000000,641.000000,641.000000,641.000000,641.000000,641.000000,641.000000,641.00000,641.000000
mean,18.355070,20.984399,30.034789,45.543214,81.535101,196.007332,326.033697,291.152262,194.609048,90.446334,34.117473,18.150858,1346.969579,39.339470,157.113105,1007.80234,142.714665
std,21.082806,27.729596,45.451082,71.556279,111.960390,196.556284,221.364643,152.647325,99.830540,74.990685,59.371274,32.711009,838.878874,47.212773,213.445888,629.33261,148.951752
min,0.000000,0.000000,0.000000,0.000000,0.900000,3.800000,11.600000,14.100000,8.600000,3.100000,1.200000,0.000000,94.600000,0.000000,1.500000,39.60000,5.600000
25%,6.900000,7.000000,7.000000,5.000000,12.100000,68.800000,206.400000,194.600000,128.800000,34.300000,6.600000,5.300000,830.400000,14.700000,27.800000,625.40000,51.600000
50%,13.300000,12.300000,12.700000,15.100000,33.900000,131.900000,293.700000,284.800000,181.300000,62.600000,12.900000,7.900000,1116.200000,27.700000,67.200000,896.60000,86.700000
75%,19.200000,24.100000,33.200000,48.300000,91.900000,226.600000,374.800000,358.100000,234.100000,130.200000,32.300000,14.900000,1530.900000,41.100000,172.400000,1193.80000,175.200000
max,144.500000,229.600000,367.900000,554.400000,733.700000,1476.200000,1820.900000,1522.100000,826.300000,517.700000,475.100000,297.700000,7229.300000,335.300000,1256.500000,5228.00000,1048.500000